name: geomesa.org
description: Website for GeoMesa

#url: "http://geomesa.org"
url: "http://localhost:4000"
repoUrl: "http://github.com/locationtech/geomesa"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments

authors:
    anthony: 
        display_name: Anthony Fox
    hunter:
        display_name: Hunter Provyn
    andrew:
        display_name: Andrew Hulbert
    chris:
        display_name: Chris Eichelberger
    emilio:
        display_name: Emilio Lahr-Vivaz


